#!/usr/bin/env python3
"""Recover the script-forwarding global functions of the official binary.

Many cGlobalScriptFuncs natives (SwingDoor_GetClosed, Lever_SetState, ...) only copy their
arguments into cScript global args, call cScript::RunGlobalFunc(<entity>, <script class>,
"_Global_<Func>") and return the global return value. This finds every such function and its
class/function strings, and emits a C++ table keyed by the recovered script declaration.

  scripts/soma-re-global-funcs.py [binary]    # writes soma/src/game/SomaGlobalFuncsTable.cpp
"""
import os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BIN = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser('~/.steam/steam/steamapps/common/SOMA/Soma_NoSteam.bin.x86_64')
OUT = os.path.join(ROOT, 'soma/src/game/SomaGlobalFuncsTable.cpp')
BASE = 0x400000
data = open(BIN, 'rb').read()


def cstr(addr):
    o = addr - BASE
    if o < 0 or o >= len(data):
        return None
    e = data.find(b'\0', o)
    try:
        return data[o:e].decode()
    except UnicodeDecodeError:
        return None


decls = {}
for line in open(os.path.join(ROOT, 'soma/data/script_api.txt')):
    f = line.rstrip('\n').split('\t')
    if f[0] == 'G' and len(f) > 2 and f[2].startswith('cGlobalScriptFuncs::'):
        decls[f[2]] = f[1]

syms = subprocess.run(['nm', '-C', '-S', '--defined-only', BIN], capture_output=True, text=True).stdout
rows = []
for line in syms.splitlines():
    m = re.match(r'([0-9a-f]+) ([0-9a-f]+) [Tt] (cGlobalScriptFuncs::.*)$', line)
    if not m or m.group(3) not in decls:
        continue
    start, size = int(m.group(1), 16), int(m.group(2), 16)
    asm = subprocess.run(['objdump', '-d', '--no-show-raw-insn', '-C', f'--start-address={start:#x}', f'--stop-address={start + size:#x}', BIN],
                         capture_output=True, text=True).stdout
    if 'cScript::RunGlobalFunc' not in asm:
        continue
    strings = [cstr(int(a, 16)) for a in re.findall(r'mov\s+\$0x([0-9a-f]+),%esi', asm)]
    strings = [s for s in strings if s is not None]
    funcs = [s for s in strings if s.startswith('_Global_')]
    if len(set(funcs)) != 1:
        continue
    i = strings.index(funcs[0])
    cls = strings[i - 1] if i > 0 and strings[i - 1].startswith('cScr') else ''
    rows.append((decls[m.group(3)], cls, funcs[0]))

rows.sort()
with open(OUT, 'w') as f:
    f.write('// Generated by scripts/soma-re-global-funcs.py from the official binary - do not edit by hand.\n')
    f.write('#include "SomaGlobalFuncsTable.h"\n\nconst cSomaGlobalFunc gvSomaGlobalFuncs[] = {\n')
    for d, c, fn in rows:
        esc = d.replace('\\', '\\\\').replace('"', '\\"')
        f.write(f'\t{{"{esc}", "{c}", "{fn}"}},\n')
    f.write('};\nconst int glSomaGlobalFuncsNum = sizeof(gvSomaGlobalFuncs) / sizeof(gvSomaGlobalFuncs[0]);\n')
print(len(rows), 'forwarding functions ->', OUT)
